# Credit: https://github.com/MathieuSoysal/Javadoc-publisher.yml

name: Deploy JavaDoc

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # If you have a protection rule on your repository, you'll need to give write permission to the workflow.
    steps:
      - name: Deploy JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: docs
          java-version: 17
          target-folder: javadoc
          project: maven
          custom-command: |
            # Copied from the default command used for Maven
            mvn javadoc:aggregate
            # Generating JavaDoc creates some .md files, so prevent them from showing up in main documentation
            for i in $(find target -name "*.md"); do
              [ -f "$i" ] || break
              echo "---" > "$i.temp"
              echo "nav_exclude: true" >> "$i.temp"
              echo "---" >> "$i.temp"
              cat "$i" >> "$i.temp"
              mv "$i.temp" "$i"
            done
